---
- hosts: erpserver
  vars_files:
    - variables.yml
  environment:
    GITHUB_TOKEN: "{{ GITHUB_TOKEN }}"
    ANSIBLE_DEBUG: 1

  tasks:

  - include: deploy-system.yml
  - include: deploy-python.yml
  - include: deploy-erp.yml




...
