---
- hosts: erpserver
  vars_files:
    - variables.yml
  environment:
    GITHUB_TOKEN: "{{ GITHUB_TOKEN }}"

  tasks:

  ### INI System users ###
  - name: Create user erp
    become: true
    user:
      name: erp
      password: 'erp'
      groups: # Empty by default, here we give it some groups
       - sudo
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      system: no             # Defaults to no
      createhome: yes        # Defaults to yes
      home: /home/erp  # Defaults to /home/<username>

  ### END System uers ###

  ### INI System packages ###
  - name: Install Ubuntu packages for OpenERP Server
    become: true
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - vim
      - tmux
      - htop
      - libxslt1-dev
      - python2.7
      - python-dev
      - libxml2-dev
      - zlib1g-dev
      - postgresql-server-dev-all
      - libjpeg-dev
      - redis-server
      - postgresql
      - libffi-dev
      - mongodb-server
      - virtualenvwrapper
      - gcc
      - g++
      - python-pip
      - pdftk
      - python-virtualenv
      - tig
  ### END System packages ###

  ### INI Python environment ###
  - name: Create virtualenv erp
    shell: ( cd /home/erp ; mkdir virtualenv; cd virtualenv; virtualenv -p /usr/bin/python2 erp ; source erp/bin/activate )
    become: yes
    become_user: erp
    args:
      executable: /bin/bash
  ### END Python environment ###

  - name: Activate virtualenv 
    shell: source /home/erp/virtualenv/erp/bin/activate
    become: yes
    become_user: erp
    args:
      executable: /bin/bash

  - name: Creates .ssh directory for root
    become: yes
    become_user: erp
    file: path=/home/erp/.ssh state=directory

  # This public key is set on Github repo Settings under "Deploy keys"
  - name: Upload the private key used for Github cloning
    become: yes
    become_user: erp
    copy: 
      src: "{{ SSH_KEY }}" 
      dest: /home/erp/.ssh/github.pub

  - name: Correct SSH deploy key permissions
    become: yes
    become_user: erp
    file: dest=/home/erp/.ssh/github.pub mode=0600

  - name: Set authorized key took from file
    authorized_key:
      user: erp
      state: present
      key: "https://github.com/{{ GITHUB_USER }}.keys"
    become: yes
    become_user: erp


  ### INI Pip install requirements ###
  - name: Copy requirements.txt file of pip packages
    copy: src=requirements.txt dest=/home/erp
    become: yes
    become_user: erp

  - name: Installing python libraries (PIP) using requirements.txt file
    pip:
      requirements: requirements.txt
      chdir: /home/erp
      virtualenv: /home/erp/virtualenv/erp/bin
    become: yes
    become_user: erp
  ### END Pip install requirements ###

  ### INI Clone repositories ###
  - name: Create src folder
    file:
      path: /home/erp/src
      recurse: yes
      state: directory
      owner: erp
      group: erp
      mode: 0755
    become: yes
    become_user: erp

  - name: git clone repositories of GISCE
    become: yes
    become_user: erp
    git: 
         repo: "git@github.com:gisce/{{ item.repo }}.git"
         dest: "{{ item.dest }}"
         force: yes
    with_items:
      -
        dest: "{{ SRC_PATH }}/aeroo"
        repo: aeroo
        version: openerp5
      -
        dest: "{{ SRC_PATH }}/aeroolib"
        repo: aeroolib
        version: openerp5
      -
        dest: "{{ SRC_PATH }}/mongodb_backend"
        repo: mongodb_backend
        version: master
      -
        dest: "{{ SRC_PATH }}/oorq"
        repo: oorq
        version: api_v5
      -
        dest: "{{ SRC_PATH }}/ooquery"
        repo: ooquery
        version: master
      -
        dest: "{{ SRC_PATH }}/openerp-sentry"
        repo: openerp-sentry
        version: v5_legacy
      -
        dest: "{{ SRC_PATH }}/poweremail"
        repo: poweremail
        version: v5_backport
      -
        dest: "{{ SRC_PATH }}/poweremail_oorq"
        repo: poweremail_oorq
        version: master
      -
        dest: "{{ SRC_PATH }}/spawn_oop"
        repo: spawn_oop
        version: master
      -
        dest: "{{ SRC_PATH }}/ws_transactions"
        repo: ws_transactions
        version: master
      -
        dest: "{{ SRC_PATH }}/sepa"
        repo: sepa
        version: master
      -
        dest: "{{ SRC_PATH }}/libFacturacioATR"
        repo: libFacturacioATR
        version: master
      -
        dest: "{{ SRC_PATH }}/switching"
        repo: switching
        version: master
      -
        dest: "{{ SRC_PATH }}/libComXML"
        repo: libComXML
        version: master
      -
        dest: "{{ SRC_PATH }}/cchloader"
        repo: cchloader
        version: gisce
      -
        dest: "{{ SRC_PATH }}/sippers"
        repo: sippers
        version: master
      -
        dest: "{{ SRC_PATH }}/ir_attachment_mongodb"
        repo: ir_attachment_mongodb
        version: master
      -
        dest: "{{ SRC_PATH }}/qreu"
        repo: qreu
        version: master
      -
        dest: "{{ SRC_PATH }}/enerdata"
        repo: enerdata
        version: master
      -
        dest: "{{ SRC_PATH }}/ooop"
        repo: ooop
        version: xmlrpc_transaction
      -
        dest: "{{ SRC_PATH }}/arquia"
        repo: arquia
        version: master
      -
        dest: "{{ SRC_PATH }}/sii"
        repo: sii
        version: master
      -
        dest: "{{ SRC_PATH }}/empowering"
        repo: empowering
        version: master
      -
        dest: "{{ SRC_PATH }}/gestionatr"
        repo: gestionatr
        version: master
...
